import { subscribeToPlatformEvents } from "@/lib/events/outbox-dispatcher"
import { commitWithEvents } from "@/lib/events/outbox-publisher"
import { createEventEnvelope, type PlatformEvent } from "@/lib/events/schemas"
import { listPredictions, saveOutcome } from "../store"
import type { MLOutcome } from "../types"
export async function collectOutcome(input:{predictionId:string; actualOutcome:number|string|boolean; groundTruthSource:string; observedAt?:string}): Promise<MLOutcome> { const now=input.observedAt??new Date().toISOString(); const outcome:MLOutcome={id:crypto.randomUUID(),predictionId:input.predictionId,actualOutcome:input.actualOutcome,groundTruthSource:input.groundTruthSource,observedAt:now}; const events:PlatformEvent[]=[createEventEnvelope({eventType:"OutcomeObserved",aggregateType:"ml",aggregateId:input.predictionId,idempotencyKey:`ml:${input.predictionId}:outcome:${input.groundTruthSource}`,payload:{predictionId:input.predictionId,actualOutcome:input.actualOutcome,groundTruthSource:input.groundTruthSource,observedAt:now}} as any)]; return commitWithEvents(async()=>saveOutcome(outcome),events) }
export async function collectDomainOutcome(event: PlatformEvent): Promise<MLOutcome | undefined> { const payload=event.payload as Record<string, unknown>; const key=typeof payload.predictionId==="string"?payload.predictionId:undefined; if(!key) return undefined; const actual=event.eventType.includes("DroppedOut") ? 1 : event.eventType.includes("Graduated") || event.eventType.includes("Completed") ? 0 : payload.actualOutcome; if(actual===undefined) return undefined; return collectOutcome({predictionId:key,actualOutcome:actual as number|string|boolean,groundTruthSource:event.eventType}) }
export function wireOutcomeCollector(): () => void { return subscribeToPlatformEvents("*", async (event) => { await collectDomainOutcome(event) }) }
export async function collectLatestOutcomeForModel(modelType:string, actualOutcome:number|string|boolean, source:string): Promise<MLOutcome | undefined> { const p=(await listPredictions()).find(p=>p.modelType===modelType); return p ? collectOutcome({predictionId:p.id,actualOutcome,groundTruthSource:source}) : undefined }
