import { commitWithEvents } from "@/lib/events/outbox-publisher"
import { createEventEnvelope, type PlatformEvent } from "@/lib/events/schemas"
import { getDb } from "@/lib/persistence"
import { schemeBudgetSchema, type SchemeBudget } from "@/lib/schemes/schemas"
import { getScheme } from "./scheme-store"

const budgets = new Map<string, SchemeBudget>()
const key = (schemeId: string, fiscalYear = "2026-27") => `${schemeId}:${fiscalYear}`
const now = () => new Date().toISOString()
function event(type: PlatformEvent["eventType"], budget: SchemeBudget, extra: Record<string, unknown> = {}): PlatformEvent { return createEventEnvelope({ eventType: type as any, aggregateType: "scheme", aggregateId: budget.schemeId, idempotencyKey: `scheme:${budget.schemeId}:${type}:${budget.updatedAt}:${budget.released}:${budget.utilized}`, payload: { schemeId: budget.schemeId, fiscalYear: budget.fiscalYear, allocated: budget.allocated, released: budget.released, utilized: budget.utilized, balance: budget.balance, ...extra } } as any) }
async function save(b: SchemeBudget) { const db = getDb(); if (db) { const { error } = await db.from("scheme_budgets").upsert({ scheme_id: b.schemeId, fiscal_year: b.fiscalYear, allocated: b.allocated, released: b.released, utilized: b.utilized, updated_at: b.updatedAt }, { onConflict: "scheme_id,fiscal_year" }); if (error) throw error } else budgets.set(key(b.schemeId, b.fiscalYear), structuredClone(b)) }
export function resetSchemeBudgetStore(): void { budgets.clear() }
export async function allocateBudget(schemeId: string, amount: number, fiscalYear = "2026-27"): Promise<void> { if (!(await getScheme(schemeId))) throw new Error(`Scheme not found: ${schemeId}`); const b = schemeBudgetSchema.parse({ schemeId, fiscalYear, allocated: amount, released: 0, utilized: 0, balance: amount, updatedAt: now() }); await commitWithEvents(async () => save(b), [event("BudgetAllocated", b), event("SchemeBudgetUpdated", b)]) }
export async function releaseFunds(schemeId: string, amount: number, fiscalYear = "2026-27"): Promise<void> { const b = await getBudgetStatus(schemeId, fiscalYear); if (b.released + amount > b.allocated) throw new Error("Cannot release more than allocated budget"); const n = schemeBudgetSchema.parse({ ...b, released: b.released + amount, updatedAt: now() }); await commitWithEvents(async () => save(n), [event("FundsReleased", n, { amount }), event("SchemeBudgetUpdated", n)]) }
export async function recordUtilization(schemeId: string, amount: number, purpose: string, fiscalYear = "2026-27"): Promise<void> { const b = await getBudgetStatus(schemeId, fiscalYear); if (b.utilized + amount > b.released) throw new Error("Cannot utilize more than released funds"); const n = schemeBudgetSchema.parse({ ...b, utilized: b.utilized + amount, balance: b.allocated - (b.utilized + amount), updatedAt: now() }); await commitWithEvents(async () => save(n), [event("FundsUtilized", n, { amount, purpose }), event("SchemeBudgetUpdated", n)]) }
export async function getBudgetStatus(schemeId: string, fiscalYear = "2026-27"): Promise<SchemeBudget> { const db = getDb(); if (db) { const { data, error } = await db.from("scheme_budgets").select("*").eq("scheme_id", schemeId).eq("fiscal_year", fiscalYear).maybeSingle(); if (error) throw error; if (data) return schemeBudgetSchema.parse({ schemeId: data.scheme_id, fiscalYear: data.fiscal_year, allocated: Number(data.allocated), released: Number(data.released), utilized: Number(data.utilized), balance: Number(data.balance ?? Number(data.allocated) - Number(data.utilized)), updatedAt: data.updated_at }) } return budgets.get(key(schemeId, fiscalYear)) ?? schemeBudgetSchema.parse({ schemeId, fiscalYear, allocated: 0, released: 0, utilized: 0, balance: 0, updatedAt: now() }) }
