// Live AI agents — a real LLM-backed adapter behind the AgentProvider port.
// Calls an OpenAI-compatible chat-completions endpoint so the 8 specialised
// agents become genuinely generative once a key is configured. Selected only when
// INTEGRATION_AGENTS=live; otherwise the registry keeps the deterministic mock.
//
// Config:
//   INTEGRATION_AGENTS=live   — flip this adapter on
//   AGENTS_API_KEY=...        — LLM API key (required for live)
//   AGENTS_API_URL=...        — chat-completions endpoint (default OpenAI)
//   AGENTS_MODEL=...          — model id (default gpt-4o-mini)

import type { AgentName, AgentProvider, AgentResponse, IntegrationResult } from "../types"
import { httpJson } from "../http"
import { agentsApiKey, agentsApiUrl, agentsModel } from "../config"

// Per-agent system prompts — scope and guardrails for each specialised agent.
const SYSTEM_PROMPTS: Record<AgentName, string> = {
  curriculum:
    "You are the Curriculum Agent for Tamil Nadu's school education OS. Help with NCF 2023 / TN curriculum, lesson plans and Tamil-first content. Be concise and practical.",
  assessment:
    "You are the Assessment Agent. Help with item generation, evaluation rubrics, knowledge tracing and the Holistic Progress Card. Be precise and pedagogically sound.",
  counselling:
    "You are the Counselling Agent. Provide supportive career guidance and well-being information. You are not a clinician; for any risk of harm, advise immediate human counsellor handoff. Be empathetic and careful.",
  operations:
    "You are the Operations Agent for daily school operations: attendance, substitution, procurement and meal management. Be efficient and checklist-oriented.",
  compliance:
    "You are the Compliance Agent for RTE / RPwD / DPDP / POCSO / POSH and school recognition. Cite the relevant norm and flag anything needing legal/human review. Be exact and conservative.",
  analytics:
    "You are the Analytics Agent for dropout prediction, learning-gap and scheme-leakage detection. Explain findings in plain language with caveats about data limits.",
  communication:
    "You are the Communication Agent for multi-channel, multilingual parent and stakeholder messaging. Draft clear, respectful messages; keep them short and translatable.",
  welfare:
    "You are the Welfare Agent for scheme eligibility, benefit calculation and DBT. Be accurate; never assert a disbursement is final — high-stakes actions require human approval.",
}

interface ChatCompletionResponse {
  choices?: { message?: { content?: string } }[]
  model?: string
}

export const liveAgents: AgentProvider = {
  async invoke(call): Promise<IntegrationResult<AgentResponse>> {
    const key = agentsApiKey()
    if (!key) {
      return { ok: false, error: "AGENTS_API_KEY not configured", mode: "live", traceId: "live-unconfigured" }
    }

    const userContent = call.context
      ? `${call.input}\n\nContext:\n${JSON.stringify(call.context)}`
      : call.input

    const res = await httpJson<ChatCompletionResponse>(agentsApiUrl(), {
      method: "POST",
      headers: { authorization: `Bearer ${key}` },
      timeoutMs: 30000,
      body: {
        model: agentsModel(),
        temperature: 0.2,
        messages: [
          { role: "system", content: SYSTEM_PROMPTS[call.agent] },
          { role: "user", content: userContent },
        ],
      },
    })

    if (!res.ok) {
      return { ok: false, error: res.error ?? "LLM request failed", mode: "live", traceId: res.traceId }
    }

    const output = res.data?.choices?.[0]?.message?.content?.trim()
    if (!output) {
      return { ok: false, error: "LLM returned no content", mode: "live", traceId: res.traceId }
    }

    return {
      ok: true,
      data: {
        output,
        // Live generations are presented assertively; high-stakes gating still
        // applies downstream via the agent's requiresApproval flag.
        confidence: 0.9,
        reasoning: `Generated by ${res.data?.model ?? agentsModel()} via live LLM.`,
      },
      mode: "live",
      traceId: res.traceId,
    }
  },
}
