import {
  LayoutDashboard,
  BookOpen,
  FileText,
  Users,
  UserCog,
  Building,
  Settings,
  ClipboardList,
  BarChart3,
  Award,
  Folder,
  Target,
  ShieldCheck,
  BookMarked,
  GraduationCap,
  Presentation,
  Landmark,
  Network,
  Database,
  FileLock,
  Palette,
  Layers,
  Heart,
  Banknote,
  Users2,
  CheckSquare,
  AlertTriangle,
  FileBarChart,
  Globe,
  MessageSquare,
  IndianRupee,
  CalendarDays,
  TrendingUp,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

export interface NavItem {
  title: string
  href: string
  icon: LucideIcon
  label?: string
  disabled?: boolean
  external?: boolean
  items?: NavItem[]
  isHeader?: boolean
}

export const dashboardNavConfig: Record<string, NavItem[]> = {
  ADMIN: [
    { title: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard },
    { title: "NEP Tracking", href: "/tracking/dashboard", icon: Target },
    { title: "Policies", href: "/policies", icon: FileText },
    { title: "Schemes", href: "/schemes", icon: Layers },
    { title: "Governance", href: "/governance/organizational-units", icon: Network },
    { title: "Roles & Permissions", href: "/governance/roles", icon: ShieldCheck },
    { title: "User Management", href: "/admin/governance/users", icon: Users },
    { title: "Milestones", href: "/tracking/milestones", icon: CheckSquare },
    { title: "Challenges", href: "/tracking/challenges", icon: AlertTriangle },
    { title: "Stakeholders", href: "/tracking/stakeholders", icon: Users2 },
    { title: "Reports & Analytics", href: "/tracking/reports", icon: FileBarChart },
    { title: "Governance Overview", href: "/governance/dashboard", icon: Globe },
    { title: "Audit Log", href: "/admin/audit-log", icon: ShieldCheck },
    { title: "AI Agents", href: "/ai-agents", icon: Layers },
    { title: "APAAR Identity", href: "/apaar", icon: Database },
    { title: "Scheme Disbursement", href: "/dbt", icon: IndianRupee },
    { title: "Multilingual & Voice", href: "/multilingual", icon: Globe },
    { title: "Consent & Audit", href: "/consent", icon: FileLock },
    { title: "Accessibility", href: "/accessibility", icon: Heart },
  ],
  TEACHER: [
    { title: "Dashboard", href: "/teacher/dashboard", icon: LayoutDashboard },
    { title: "My Courses", href: "/teacher/courses", icon: BookOpen },
    { title: "Create Course", href: "/teacher/courses/create", icon: BookMarked },
  ],
  STUDENT: [
    { title: "Dashboard", href: "/student/dashboard", icon: LayoutDashboard },
    { title: "My Courses", href: "/student/courses", icon: BookOpen },
    { title: "Assignments", href: "/student/assignments", icon: ClipboardList },
    { title: "My Grades", href: "/student/grades", icon: Award },
    { title: "Resources", href: "/student/resources", icon: Folder },
    { title: "Announcements", href: "/student/announcements", icon: Presentation },
  ],
  PRINCIPAL: [
    { title: "Dashboard", href: "/principal/dashboard", icon: LayoutDashboard },
    { title: "Students (SIS)", href: "/principal/students", icon: GraduationCap },
    { title: "Staff Management", href: "/principal/staff", icon: Users },
    { title: "Assessment & Exams", href: "/principal/assessment", icon: ClipboardList },
    { title: "Fee Management", href: "/principal/fee-management", icon: Banknote },
    { title: "School Health", href: "/principal/health", icon: Heart },
    { title: "Compliance", href: "/principal/compliance", icon: ShieldCheck },
    { title: "Policies", href: "/policies", icon: FileText },
    { title: "Schemes", href: "/schemes", icon: Layers },
    { title: "NEP Tracking", href: "/tracking/dashboard", icon: Target },
    { title: "Announcements", href: "/principal/announcements", icon: Presentation },
  ],
  SUBJECT_INCHARGE: [
    { title: "Dashboard", href: "/subject-incharge/dashboard", icon: LayoutDashboard },
    { title: "Curriculum Management", href: "/subject-incharge/curriculum", icon: BookMarked },
    { title: "Resource Allocation", href: "/subject-incharge/resources", icon: Folder },
    { title: "Teacher Coordination", href: "/subject-incharge/teachers", icon: Users },
    { title: "Student Performance", href: "/subject-incharge/students/performance", icon: BarChart3 },
  ],
  ACADEMIC_HEAD: [
    { title: "Dashboard", href: "/academic-head/dashboard", icon: LayoutDashboard },
    { title: "Curriculum Development", href: "/academic-head/curriculum", icon: BookMarked },
    { title: "Assessment & Evaluation", href: "/academic-head/assessment", icon: ClipboardList },
    { title: "Teacher PD", href: "/academic-head/teacher-dev", icon: GraduationCap },
    { title: "Academic Planning", href: "/academic-head/planning", icon: Target },
  ],
  INSTITUTION_HEAD: [
    { title: "Dashboard", href: "/institution-head/dashboard", icon: LayoutDashboard },
    { title: "Strategic Planning", href: "/institution-head/strategy", icon: Target },
    { title: "Policy Management", href: "/institution-head/policies", icon: FileText },
    { title: "Stakeholder Management", href: "/institution-head/stakeholders", icon: Network },
    { title: "Resource Management", href: "/institution-head/resources", icon: Landmark },
  ],
  PARENT: [
    { title: "Dashboard", href: "/parent/dashboard", icon: LayoutDashboard },
    { title: "Attendance", href: "/parent/attendance", icon: CalendarDays },
    { title: "Performance", href: "/parent/performance", icon: TrendingUp },
    { title: "Fee Management", href: "/parent/fees", icon: IndianRupee },
    { title: "Communication", href: "/parent/communication", icon: MessageSquare },
  ],
  CRCC: [{ title: "Dashboard", href: "/crcc/dashboard", icon: LayoutDashboard }],
  BEO: [{ title: "Dashboard", href: "/beo/dashboard", icon: LayoutDashboard }],
  DEO: [{ title: "Dashboard", href: "/deo/dashboard", icon: LayoutDashboard }],
  DIRECTOR: [{ title: "Dashboard", href: "/director/dashboard", icon: LayoutDashboard }],
  SECRETARY: [{ title: "Dashboard", href: "/secretary/dashboard", icon: LayoutDashboard }],
  MINISTER: [{ title: "Dashboard", href: "/minister/dashboard", icon: LayoutDashboard }],
  VENDOR: [{ title: "Dashboard", href: "/vendor/dashboard", icon: LayoutDashboard }],
  RESEARCHER: [{ title: "Dashboard", href: "/researcher/dashboard", icon: LayoutDashboard }],
  PUBLIC: [{ title: "Dashboard", href: "/public/dashboard", icon: LayoutDashboard }],
}
