import {
  LayoutDashboard,
  BookOpen,
  FileText,
  Users,
  UserCog,
  Building,
  Settings,
  ClipboardList,
  BarChart3,
  Award,
  Folder,
  Target,
  ShieldCheck,
  BookMarked,
  GraduationCap,
  Presentation,
  Landmark,
  Network,
  Database,
  FileLock,
  Palette,
  Layers,
  Heart,
  Banknote,
  Users2,
  CheckSquare,
  AlertTriangle,
  FileBarChart,
  Globe,
  MessageSquare,
  IndianRupee,
  CalendarDays,
  TrendingUp,
  Utensils,
  FileCheck2,
  BedDouble,
  Bus,
  Stethoscope,
  Scale,
  Package,
  Leaf,
  Vote,
  Brain,
  ScanLine,
  Share2,
  BadgeCheck,
  Wrench,
  Siren,
  Stamp,
  Library,
  School,
  Fingerprint,
  Plug,
  HeartPulse,
  Sun,
  LineChart,
  CalendarCheck,
  Send,
  Accessibility,
  UserPlus,
  Hammer,
  Backpack,
  FileOutput,
  Cctv,
  Droplets,
  BookA,
  Sprout,
  ScrollText,
  FlaskConical,
  Medal,
  Map,
  Flame,
  Monitor,
  Mic,
  UserMinus,
  BookCopy,
  Dumbbell,
  Activity,
  HeartHandshake,
  Sunrise,
  PiggyBank,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

export interface NavItem {
  title: string
  href: string
  icon: LucideIcon
  label?: string
  disabled?: boolean
  external?: boolean
  items?: NavItem[]
  isHeader?: boolean
}

// The 43 deep / durable modules (driven by the Go backbone + PostgreSQL). Surfaced as a single navigable section
// so they are reachable from the sidebar, not only via /directory. Kept in sync with lib/governance/durable-modules.ts.
export const durableModuleNav: NavItem[] = [
  { title: "▸ Durable Modules", href: "/directory", icon: Layers },
  { title: "Establishment & Posts", href: "/establishment", icon: Building },
  { title: "Fee & Finance Ledger", href: "/fee-ledger", icon: IndianRupee },
  { title: "RTE Admissions", href: "/rte-admissions", icon: GraduationCap },
  { title: "Grievance Cases", href: "/grievance-cases", icon: MessageSquare },
  { title: "Grievance Approvals", href: "/grievance-approvals", icon: CheckSquare },
  { title: "Scholarship / DBT", href: "/dbt-scholarship", icon: Banknote },
  { title: "Mid-Day Meal", href: "/mid-day-meal", icon: Utensils },
  { title: "School Transport", href: "/school-transport", icon: Bus },
  { title: "Health Immunisation", href: "/health-immunisation", icon: HeartPulse },
  { title: "Free-Supply Entitlement", href: "/free-supply", icon: Package },
  { title: "Class Timetable", href: "/class-timetable", icon: CalendarDays },
  { title: "School Library", href: "/school-library", icon: Library },
  { title: "Estate & Asset Register", href: "/estate-register", icon: Wrench },
  { title: "Parent–Teacher Meetings", href: "/parent-teacher-meetings", icon: Users2 },
  { title: "RBSK Health Screening", href: "/health-screening", icon: Stethoscope },
  { title: "Teacher CPD", href: "/teacher-cpd", icon: GraduationCap },
  { title: "Student Attendance", href: "/student-attendance", icon: CalendarCheck },
  { title: "Academic Calendar", href: "/events-calendar", icon: CalendarDays },
  { title: "Examinations & Results", href: "/exam-results", icon: FileBarChart },
  { title: "User Directory & IAM", href: "/user-directory", icon: Users },
  { title: "Staff Leave", href: "/leave-approvals", icon: FileCheck2 },
  { title: "Audit Trail & Ledger", href: "/audit-trail", icon: FileLock },
  { title: "School Inspection", href: "/school-inspection", icon: ClipboardList },
  { title: "Transfer Certificates", href: "/transfer-certificate", icon: Stamp },
  { title: "Staff Attendance & Payable Days", href: "/employee-attendance", icon: CalendarCheck },
  { title: "School Grant Utilisation", href: "/school-grants", icon: Banknote },
  { title: "Lesson Plans", href: "/lesson-plan", icon: BookOpen },
  { title: "Period Attendance & Delivery", href: "/period-attendance", icon: CalendarCheck },
  { title: "SMC Meetings & Resolutions", href: "/smc-meetings", icon: Vote },
  { title: "Bonafide Certificate Register", href: "/bonafide-register", icon: Stamp },
  { title: "Teacher Transfer & Posting", href: "/teacher-transfer", icon: UserCog },
  { title: "Hostel Allocation & Occupancy", href: "/hostel-occupancy", icon: BedDouble },
  { title: "Campus Facilities (CIFM)", href: "/campus-facilities", icon: Hammer },
  { title: "Native AI Language Lab", href: "/language-lab", icon: Globe },
  { title: "Procurement & GeM", href: "/gem-procurement", icon: IndianRupee },
  { title: "School Sanitation & WASH", href: "/wash-register", icon: Droplets },
  { title: "Sports & Co-curricular Competitions", href: "/sports-competitions", icon: Medal },
  { title: "School Stores & Inventory", href: "/stock-register", icon: Package },
  { title: "Visitor & Gate Management", href: "/visitor-gate", icon: Cctv },
  { title: "Water Quality Testing", href: "/water-testing", icon: Droplets },
  { title: "Notice Board & Circulars", href: "/notice-board", icon: ScrollText },
  { title: "Diagnostic & Remedial (FLN)", href: "/remedial-batches", icon: Target },
  { title: "Co-curricular Registration", href: "/event-registration", icon: Award },
]

export const dashboardNavConfig: Record<string, NavItem[]> = {
  ADMIN: [
    { title: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard },
    { title: "Today (daily loop)", href: "/today", icon: Sun },
    { title: "Remedial / NIPUN Classes", href: "/remedial", icon: BookOpen },
    { title: "Diagnostic Learning-Level", href: "/diagnostic", icon: Target },
    { title: "Holistic Progress Card", href: "/hpc", icon: ClipboardList },
    { title: "Homework & Assignments", href: "/homework", icon: ClipboardList },
    { title: "Certificates", href: "/certificates", icon: FileText },
    { title: "Teacher Profile", href: "/teacher-profile", icon: UserCog },
    { title: "Communications", href: "/communications", icon: Send },
    { title: "Notice Board & Circulars", href: "/notices", icon: FileText },
    { title: "Adoption & Retention", href: "/adoption", icon: LineChart },
    { title: "NEP Tracking", href: "/tracking/dashboard", icon: Target },
    { title: "NEP Analytics", href: "/tracking/analytics", icon: LineChart },
    { title: "Policies", href: "/policies", icon: FileText },
    { title: "Schemes", href: "/schemes", icon: Layers },
    { title: "Governance", href: "/governance/organizational-units", icon: Network },
    { title: "Roles & Permissions", href: "/governance/roles", icon: ShieldCheck },
    { title: "Access Explorer", href: "/governance/access", icon: ShieldCheck },
    { title: "Data Scope Explorer", href: "/governance/scope", icon: Network },
    { title: "Requirements Traceability", href: "/governance/traceability", icon: ClipboardList },
    { title: "Architecture Conformance", href: "/architecture", icon: Network },
    { title: "Integration Go-Live", href: "/governance/go-live", icon: Plug },
    { title: "Assurance & DPIA", href: "/governance/assurance", icon: ShieldCheck },
    { title: "Government Structure", href: "/governance/org", icon: Landmark },
    { title: "User Directory & IAM", href: "/governance/directory", icon: Users },
    { title: "User Management", href: "/admin/governance/users", icon: Users },
    { title: "Milestones", href: "/tracking/milestones", icon: CheckSquare },
    { title: "Challenges", href: "/tracking/challenges", icon: AlertTriangle },
    { title: "Stakeholders", href: "/tracking/stakeholders", icon: Users2 },
    { title: "Reports & Analytics", href: "/tracking/reports", icon: FileBarChart },
    { title: "Governance Overview", href: "/governance/dashboard", icon: Globe },
    { title: "Oversight Command Centre", href: "/governance/oversight", icon: Activity },
    { title: "Forums & Meetings (RACI)", href: "/governance/forums", icon: Vote },
    { title: "Audit Log", href: "/admin/audit-log", icon: ShieldCheck },
    { title: "AI Agents", href: "/ai-agents", icon: Layers },
    { title: "Agent Action Approvals (HITL)", href: "/ai-agents/approvals", icon: CheckSquare },
    { title: "APAAR Identity", href: "/apaar", icon: Database },
    { title: "Scheme Disbursement", href: "/dbt", icon: IndianRupee },
    { title: "Multilingual & Voice", href: "/multilingual", icon: Globe },
    { title: "Consent & Audit", href: "/consent", icon: FileLock },
    { title: "PII Classification (DPDP)", href: "/governance/pii-catalogue", icon: FileLock },
    { title: "Accessibility", href: "/accessibility", icon: Heart },
    { title: "PM POSHAN / CMBS", href: "/pm-poshan", icon: Utensils },
    { title: "Mid-Day Meal Register", href: "/mdm", icon: Utensils },
    { title: "Disciplinary / Incidents", href: "/discipline", icon: AlertTriangle },
    { title: "Anti-Ragging & Safety", href: "/safety", icon: ShieldCheck },
    { title: "Lost & Found / Gate Pass", href: "/lost-found", icon: Package },
    { title: "Cook-cum-Helper", href: "/cooks", icon: Utensils },
    { title: "Examination Security", href: "/exams", icon: FileCheck2 },
    { title: "Exam Seating & Halls", href: "/exam-seating", icon: FileCheck2 },
    { title: "Result Publication", href: "/results", icon: FileBarChart },
    { title: "Question Bank & Papers", href: "/question-bank", icon: FileText },
    { title: "Student Information System", href: "/sis", icon: GraduationCap },
    { title: "Multi-Tenancy", href: "/tenancy", icon: Network },
    { title: "Zero-Trust Security", href: "/security", icon: ShieldCheck },
    { title: "Visitor & Gate Management", href: "/visitors", icon: Users2 },
    { title: "Data Platform", href: "/data-platform", icon: Database },
    { title: "Inventory Issue/Receive", href: "/inventory", icon: Package },
    { title: "Free-Scheme Distribution", href: "/distribution", icon: Package },
    { title: "Inspection Visits", href: "/inspections", icon: CheckSquare },
    { title: "Library", href: "/library", icon: BookMarked },
    { title: "Library Circulation", href: "/circulation", icon: BookMarked },
    { title: "Career Guidance", href: "/career", icon: Target },
    { title: "RBSK Screening Entry", href: "/rbsk-screening", icon: Stethoscope },
    { title: "Transport", href: "/transport", icon: Bus },
    { title: "Transport Assignment", href: "/transport-assignment", icon: Bus },
    { title: "Bus Live Tracking", href: "/bus-tracking", icon: Bus },
    { title: "Leave Management", href: "/leave", icon: FileCheck2 },
    { title: "Leave Approvals (Workflow)", href: "/leave-approvals", icon: CheckSquare },
    { title: "Academic Calendar", href: "/academic-calendar", icon: CalendarDays },
    { title: "PTM Scheduling", href: "/ptm", icon: Presentation },
    { title: "School Health (RBSK)", href: "/rbsk", icon: Stethoscope },
    { title: "Grievances", href: "/grievance", icon: MessageSquare },
    { title: "Grievance Escalation (Workflow)", href: "/grievance-approvals", icon: MessageSquare },
    { title: "Parent Feedback", href: "/feedback", icon: Heart },
    { title: "Governance Framework", href: "/governance/framework", icon: Scale },
    { title: "School Finance", href: "/finance", icon: Banknote },
    { title: "School Development Plan", href: "/sdp", icon: Banknote },
    { title: "Scholarship Tracking", href: "/scholarships", icon: Banknote },
    { title: "Maintenance Tickets", href: "/maintenance", icon: Wrench },
    { title: "Maintenance Tickets (Workflow)", href: "/maintenance-approvals", icon: Wrench },
    { title: "Admissions & Enrolment", href: "/admissions", icon: Users },
    { title: "Admissions Approvals (Workflow)", href: "/admissions-approvals", icon: Users },
    { title: "Pre-Primary / Anganwadi", href: "/pre-primary", icon: Heart },
    { title: "CWSN / Special-Needs IEP", href: "/cwsn", icon: Accessibility },
    { title: "RTE 25% Quota", href: "/rte", icon: Scale },
    { title: "Out-of-School Children", href: "/oosc", icon: UserPlus },
    { title: "Vocational & Skills (NSQF)", href: "/vocational", icon: Hammer },
    { title: "Student Council Elections", href: "/student-council", icon: Vote },
    { title: "Bagless Days", href: "/bagless", icon: Backpack },
    { title: "Transfer Certificate (TC)", href: "/tc", icon: FileOutput },
    { title: "CCTV / Surveillance", href: "/cctv", icon: Cctv },
    { title: "Water & Sanitation Quality", href: "/water-quality", icon: Droplets },
    { title: "Reading Campaign / FLN", href: "/reading", icon: BookA },
    { title: "Eco Club & Plantation", href: "/eco-club", icon: Sprout },
    { title: "RTI Register", href: "/rti", icon: ScrollText },
    { title: "Science Exhibition / INSPIRE", href: "/science-fair", icon: FlaskConical },
    { title: "Olympiad & Competitions", href: "/competitions", icon: Medal },
    { title: "Field Trips & Excursions", href: "/excursions", icon: Map },
    { title: "Fire & Mock Drills", href: "/mock-drills", icon: Flame },
    { title: "ICT Lab / Smart Class", href: "/ict-lab", icon: Monitor },
    { title: "Guest Lectures", href: "/guest-lectures", icon: Mic },
    { title: "Teacher Vacancy & Rationalisation", href: "/vacancy", icon: UserMinus },
    { title: "Textbook Indent & Book Bank", href: "/textbooks", icon: BookCopy },
    { title: "Khelo India Fitness Test", href: "/fitness", icon: Dumbbell },
    { title: "NSS / NCC / Scouts", href: "/nss-ncc", icon: HeartHandshake },
    { title: "Morning Assembly / Bal Sabha", href: "/assembly", icon: Sunrise },
    { title: "Student Banking", href: "/student-banking", icon: PiggyBank },
    { title: "Inventory & Procurement", href: "/procurement", icon: Package },
    { title: "SMC (DAO)", href: "/smc", icon: Vote },
    { title: "SMC Resolution Approvals", href: "/smc-approvals", icon: Vote },
    { title: "Quality & Inspection", href: "/quality", icon: CheckSquare },
    { title: "Green School / ESG", href: "/green-school", icon: Leaf },
    { title: "WASH / Swachh Audit", href: "/wash-audit", icon: Leaf },
    { title: "Co-curricular & Sports", href: "/co-curricular", icon: Award },
    { title: "Sports Meet & Medals", href: "/sports", icon: Award },
    { title: "Co-curricular Registration", href: "/co-curricular-registration", icon: Award },
    { title: "Alumni Registry", href: "/alumni", icon: GraduationCap },
    { title: "Asset Register", href: "/assets", icon: Layers },
    { title: "Student Promotion", href: "/promotion", icon: TrendingUp },
    { title: "Adaptive Learning", href: "/adaptive-learning", icon: Brain },
    { title: "OCR / OMR Engine", href: "/omr", icon: ScanLine },
    { title: "Knowledge Graph", href: "/knowledge-graph", icon: Share2 },
    { title: "Verifiable Credentials", href: "/credentials", icon: BadgeCheck },
    { title: "Infrastructure & Assets", href: "/infrastructure", icon: Wrench },
    { title: "Emergency & Disaster", href: "/emergency", icon: Siren },
    { title: "School Recognition (TN 1973)", href: "/recognition", icon: Stamp },
    { title: "Recognition Approvals (Workflow)", href: "/recognition-approvals", icon: Stamp },
    { title: "Content Discovery (DIKSHA)", href: "/content", icon: Library },
    { title: "Digital E-Content Library", href: "/e-content", icon: Library },
    { title: "School Registry (UDISE+)", href: "/school-registry", icon: School },
    { title: "School Structure (5+3+3+4)", href: "/school-structure", icon: School },
    { title: "Aadhaar Auth (UIDAI)", href: "/aadhaar", icon: Fingerprint },
    { title: "Integrations Status", href: "/integrations", icon: Plug },
    { title: "System Self-Test", href: "/health", icon: HeartPulse },
    { title: "Operations & Health", href: "/ops", icon: Activity },
    { title: "Abbreviations & Glossary", href: "/glossary", icon: BookA },
    ...durableModuleNav,
  ],
  TEACHER: [
    { title: "Dashboard", href: "/teacher/dashboard", icon: LayoutDashboard },
    { title: "My Courses", href: "/teacher/courses", icon: BookOpen },
    { title: "Create Course", href: "/teacher/courses/create", icon: BookMarked },
    ...durableModuleNav,
  ],
  STUDENT: [
    { title: "Dashboard", href: "/student/dashboard", icon: LayoutDashboard },
    { title: "My Courses", href: "/student/courses", icon: BookOpen },
    { title: "Assignments", href: "/student/assignments", icon: ClipboardList },
    { title: "My Grades", href: "/student/grades", icon: Award },
    { title: "Resources", href: "/student/resources", icon: Folder },
    { title: "Announcements", href: "/student/announcements", icon: Presentation },
    ...durableModuleNav,
  ],
  PRINCIPAL: [
    { title: "Dashboard", href: "/principal/dashboard", icon: LayoutDashboard },
    { title: "Students (SIS)", href: "/principal/students", icon: GraduationCap },
    { title: "Staff Management", href: "/principal/staff", icon: Users },
    { title: "Assessment & Exams", href: "/principal/assessment", icon: ClipboardList },
    { title: "Fee Management", href: "/principal/fee-management", icon: Banknote },
    { title: "School Health", href: "/principal/health", icon: Heart },
    { title: "Compliance", href: "/principal/compliance", icon: ShieldCheck },
    { title: "Policies", href: "/policies", icon: FileText },
    { title: "Schemes", href: "/schemes", icon: Layers },
    { title: "NEP Tracking", href: "/tracking/dashboard", icon: Target },
    { title: "Announcements", href: "/principal/announcements", icon: Presentation },
    ...durableModuleNav,
  ],
  SUBJECT_INCHARGE: [
    { title: "Dashboard", href: "/subject-incharge/dashboard", icon: LayoutDashboard },
    { title: "Curriculum Management", href: "/subject-incharge/curriculum", icon: BookMarked },
    { title: "Resource Allocation", href: "/subject-incharge/resources", icon: Folder },
    { title: "Teacher Coordination", href: "/subject-incharge/teachers", icon: Users },
    { title: "Student Performance", href: "/subject-incharge/students/performance", icon: BarChart3 },
    ...durableModuleNav,
  ],
  ACADEMIC_HEAD: [
    { title: "Dashboard", href: "/academic-head/dashboard", icon: LayoutDashboard },
    { title: "Curriculum Development", href: "/academic-head/curriculum", icon: BookMarked },
    { title: "Assessment & Evaluation", href: "/academic-head/assessment", icon: ClipboardList },
    { title: "Teacher PD", href: "/academic-head/teacher-dev", icon: GraduationCap },
    { title: "Academic Planning", href: "/academic-head/planning", icon: Target },
    ...durableModuleNav,
  ],
  INSTITUTION_HEAD: [
    { title: "Dashboard", href: "/institution-head/dashboard", icon: LayoutDashboard },
    { title: "Strategic Planning", href: "/institution-head/strategy", icon: Target },
    { title: "Policy Management", href: "/institution-head/policies", icon: FileText },
    { title: "Stakeholder Management", href: "/institution-head/stakeholders", icon: Network },
    { title: "Resource Management", href: "/institution-head/resources", icon: Landmark },
    ...durableModuleNav,
  ],
  PARENT: [
    { title: "Dashboard", href: "/parent/dashboard", icon: LayoutDashboard },
    { title: "Attendance", href: "/parent/attendance", icon: CalendarDays },
    { title: "Performance", href: "/parent/performance", icon: TrendingUp },
    { title: "Fee Management", href: "/parent/fees", icon: IndianRupee },
    { title: "Communication", href: "/parent/communication", icon: MessageSquare },
    ...durableModuleNav,
  ],
  CRCC: [{ title: "Dashboard", href: "/crcc/dashboard", icon: LayoutDashboard }, ...durableModuleNav],
  BEO: [{ title: "Dashboard", href: "/beo/dashboard", icon: LayoutDashboard }, ...durableModuleNav],
  DEO: [{ title: "Dashboard", href: "/deo/dashboard", icon: LayoutDashboard }, ...durableModuleNav],
  DIRECTOR: [{ title: "Dashboard", href: "/director/dashboard", icon: LayoutDashboard }, ...durableModuleNav],
  SECRETARY: [{ title: "Dashboard", href: "/secretary/dashboard", icon: LayoutDashboard }, ...durableModuleNav],
  MINISTER: [{ title: "Dashboard", href: "/minister/dashboard", icon: LayoutDashboard }, ...durableModuleNav],
  VENDOR: [{ title: "Dashboard", href: "/vendor/dashboard", icon: LayoutDashboard }, ...durableModuleNav],
  RESEARCHER: [{ title: "Dashboard", href: "/researcher/dashboard", icon: LayoutDashboard }, ...durableModuleNav],
  PUBLIC: [{ title: "Dashboard", href: "/public/dashboard", icon: LayoutDashboard }, ...durableModuleNav],
}
