import { getDb } from "@/lib/persistence"
import { assertNonProductionMemoryAdapter } from "@/lib/runtime/production-guard"
import { mlDriftReportSchema, mlFeatureSnapshotSchema, mlModelSchema, mlOutcomeSchema, mlPredictionSchema, mlTrainingRunSchema, type MLDriftReport, type MLFeatureSnapshot, type MLModel, type MLModelType, type MLOutcome, type MLPrediction, type MLTrainingRun } from "./types"

const memory = { models: new Map<string, MLModel>(), predictions: new Map<string, MLPrediction>(), outcomes: new Map<string, MLOutcome>(), drift: new Map<string, MLDriftReport>(), training: new Map<string, MLTrainingRun>(), snapshots: new Map<string, MLFeatureSnapshot>() }
export function resetMLStore(): void { for (const map of Object.values(memory)) map.clear() }
const c = <T>(v: T): T => structuredClone(v)
function valueFromJson(v: unknown): unknown { return typeof v === "string" ? JSON.parse(v) : v }
function allowMemory(): void { assertNonProductionMemoryAdapter("ml-store") }

export async function saveModel(model: MLModel): Promise<MLModel> { const parsed = mlModelSchema.parse(model); const db = getDb(); if (db) { const { error } = await db.from("ml_models").upsert({ id: parsed.id, model_type: parsed.modelType, version: parsed.version, status: parsed.status, metrics: parsed.metrics, artifact: parsed.artifact, dataset_hash: parsed.datasetHash, high_stakes: parsed.highStakes, promoted_at: parsed.promotedAt ?? null, created_at: parsed.createdAt }, { onConflict: "id" }); if (error) throw error } else { allowMemory(); memory.models.set(parsed.id, c(parsed)) } return parsed }
export async function listModels(modelType?: MLModelType): Promise<MLModel[]> { const db = getDb(); if (db) { let q = db.from("ml_models").select("*").order("created_at", { ascending: false }); if (modelType) q = q.eq("model_type", modelType); const { data, error } = await q; if (error) throw error; return ((data ?? []) as any[]).map((r) => mlModelSchema.parse({ id: r.id, modelType: r.model_type, version: r.version, status: r.status, metrics: r.metrics, artifact: r.artifact, datasetHash: r.dataset_hash, highStakes: r.high_stakes, promotedAt: r.promoted_at ?? undefined, createdAt: r.created_at })) } allowMemory(); return [...memory.models.values()].filter((m) => !modelType || m.modelType === modelType).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(c) }
export async function getModel(id: string): Promise<MLModel | undefined> { return (await listModels()).find((m) => m.id === id) }
export async function getActiveModel(modelType: MLModelType): Promise<MLModel | undefined> { return (await listModels(modelType)).find((m) => m.status === "active") }
export async function savePrediction(prediction: MLPrediction): Promise<MLPrediction> { const parsed = mlPredictionSchema.parse(prediction); const db = getDb(); if (db) { const { error } = await db.from("ml_predictions").upsert({ id: parsed.id, model_id: parsed.modelId, model_type: parsed.modelType, model_version: parsed.modelVersion, input_features: parsed.inputFeatures, prediction: parsed.prediction, confidence: parsed.confidence, created_at: parsed.createdAt }, { onConflict: "id" }); if (error) throw error } else { allowMemory(); memory.predictions.set(parsed.id, c(parsed)) } return parsed }
export async function listPredictions(modelType?: MLModelType): Promise<MLPrediction[]> { const db = getDb(); if (db) { let q = db.from("ml_predictions").select("*").order("created_at", { ascending: false }); if (modelType) q = q.eq("model_type", modelType); const { data, error } = await q; if (error) throw error; return ((data ?? []) as any[]).map((r) => mlPredictionSchema.parse({ id: r.id, modelId: r.model_id, modelType: r.model_type, modelVersion: r.model_version, inputFeatures: r.input_features, prediction: valueFromJson(r.prediction), confidence: Number(r.confidence), createdAt: r.created_at })) } allowMemory(); return [...memory.predictions.values()].filter((p) => !modelType || p.modelType === modelType).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(c) }
export async function saveOutcome(outcome: MLOutcome): Promise<MLOutcome> { const parsed = mlOutcomeSchema.parse(outcome); const db = getDb(); if (db) { const { error } = await db.from("ml_outcomes").upsert({ id: parsed.id, prediction_id: parsed.predictionId, actual_outcome: parsed.actualOutcome, ground_truth_source: parsed.groundTruthSource, observed_at: parsed.observedAt }, { onConflict: "prediction_id,ground_truth_source" }); if (error) throw error } else { allowMemory(); memory.outcomes.set(parsed.id, c(parsed)) } return parsed }
export async function listOutcomes(): Promise<MLOutcome[]> { const db = getDb(); if (db) { const { data, error } = await db.from("ml_outcomes").select("*").order("observed_at", { ascending: false }); if (error) throw error; return ((data ?? []) as any[]).map((r) => mlOutcomeSchema.parse({ id: r.id, predictionId: r.prediction_id, actualOutcome: valueFromJson(r.actual_outcome), groundTruthSource: r.ground_truth_source, observedAt: r.observed_at })) } allowMemory(); return [...memory.outcomes.values()].sort((a,b)=>b.observedAt.localeCompare(a.observedAt)).map(c) }
export async function saveDriftReport(report: MLDriftReport): Promise<MLDriftReport> { const parsed = mlDriftReportSchema.parse(report); const db = getDb(); if (db) { const { error } = await db.from("ml_drift_reports").insert({ id: parsed.id, model_id: parsed.modelId, model_type: parsed.modelType, model_version: parsed.modelVersion, drift_type: parsed.driftType, magnitude: parsed.magnitude, threshold: parsed.threshold, severity: parsed.severity, detected_at: parsed.detectedAt }); if (error) throw error } else { allowMemory(); memory.drift.set(parsed.id, c(parsed)) } return parsed }
export async function listDriftReports(modelType?: MLModelType): Promise<MLDriftReport[]> { const db = getDb(); if (db) { let q = db.from("ml_drift_reports").select("*").order("detected_at", { ascending: false }); if (modelType) q = q.eq("model_type", modelType); const { data, error } = await q; if (error) throw error; return ((data ?? []) as any[]).map((r) => mlDriftReportSchema.parse({ id: r.id, modelId: r.model_id, modelType: r.model_type, modelVersion: r.model_version, driftType: r.drift_type, magnitude: Number(r.magnitude), threshold: Number(r.threshold), severity: r.severity, detectedAt: r.detected_at })) } allowMemory(); return [...memory.drift.values()].filter((r) => !modelType || r.modelType === modelType).sort((a,b)=>b.detectedAt.localeCompare(a.detectedAt)).map(c) }
export async function saveTrainingRun(run: MLTrainingRun): Promise<MLTrainingRun> { const parsed = mlTrainingRunSchema.parse(run); const db = getDb(); if (db) { const { error } = await db.from("ml_training_runs").upsert({ id: parsed.id, model_type: parsed.modelType, version: parsed.version, metrics: parsed.metrics, dataset_hash: parsed.datasetHash, duration_seconds: parsed.durationSeconds, created_at: parsed.createdAt }, { onConflict: "model_type,version,dataset_hash" }); if (error) throw error } else { allowMemory(); memory.training.set(parsed.id, c(parsed)) } return parsed }
export async function saveFeatureSnapshot(snapshot: MLFeatureSnapshot): Promise<MLFeatureSnapshot> { const parsed = mlFeatureSnapshotSchema.parse(snapshot); const db = getDb(); if (db) { const { error } = await db.from("ml_feature_snapshots").upsert({ id: parsed.id, model_type: parsed.modelType, dataset_hash: parsed.datasetHash, feature_distributions: parsed.featureDistributions, created_at: parsed.createdAt }, { onConflict: "model_type,dataset_hash" }); if (error) throw error } else { allowMemory(); memory.snapshots.set(parsed.id, c(parsed)) } return parsed }
export async function listFeatureSnapshots(modelType?: MLModelType): Promise<MLFeatureSnapshot[]> { const db = getDb(); if (db) { let q = db.from("ml_feature_snapshots").select("*").order("created_at", { ascending: false }); if (modelType) q = q.eq("model_type", modelType); const { data, error } = await q; if (error) throw error; return ((data ?? []) as any[]).map((r) => mlFeatureSnapshotSchema.parse({ id: r.id, modelType: r.model_type, datasetHash: r.dataset_hash, featureDistributions: r.feature_distributions, createdAt: r.created_at })) } allowMemory(); return [...memory.snapshots.values()].filter((s) => !modelType || s.modelType === modelType).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(c) }
