import { commitWithEvents } from "@/lib/events/outbox-publisher"
import { createEventEnvelope, type PlatformEvent } from "@/lib/events/schemas"
import { listModels, listOutcomes, listPredictions, saveDriftReport } from "../store"
import { populationStabilityIndex } from "../drift/psi"
import { conceptDrift } from "../drift/concept-drift"
import type { MLDriftReport, MLModel, NumericVector } from "../types"
function values(rows: NumericVector[], feature:string){ return rows.map(r=>r[feature]??0) }
export async function runDriftMonitor(now=new Date()): Promise<{checked:number; drift:number; retraining:number}> { const active=(await listModels()).filter(m=>m.status==="active"); let drift=0,retraining=0; for(const model of active){ const predictions=(await listPredictions(model.modelType)).filter(p=>p.modelId===model.id); if(!predictions.length) continue; const recent=predictions.map(p=>p.inputFeatures); const reports:MLDriftReport[]=[]; for(const feature of model.artifact.features){ const score=populationStabilityIndex(model.artifact.baseline[feature]??[], values(recent,feature)); if(score.severity!=="none") reports.push(report(model,"data",score.magnitude,score.threshold,score.severity,now)) }
 const outcomes=await listOutcomes(); const perf=conceptDrift(predictions,outcomes,model.metrics.accuracy); if(perf.severity!=="none") reports.push(report(model,"performance",perf.magnitude,perf.threshold,perf.severity,now)); for(const r of reports){ const events:PlatformEvent[]=[createEventEnvelope({eventType:"DriftDetected",aggregateType:"ml",aggregateId:model.id,idempotencyKey:`ml:${model.id}:drift:${r.driftType}:${r.detectedAt}:${r.magnitude}`,payload:{modelType:model.modelType,modelVersion:model.version,driftType:r.driftType,driftMagnitude:r.magnitude,thresholdBreached:r.threshold,severity:r.severity}} as any)]; if(r.severity==="critical") { events.push(createEventEnvelope({eventType:"RetrainingTriggered",aggregateType:"ml",aggregateId:model.id,idempotencyKey:`ml:${model.id}:retrain:${r.detectedAt}`,payload:{modelType:model.modelType,reason:`${r.driftType} drift ${r.magnitude} exceeded ${r.threshold}`,datasetSnapshotId:model.datasetHash}} as any)); retraining++ } await commitWithEvents(async()=>saveDriftReport(r),events); drift++ }
 }
 return {checked:active.length,drift,retraining} }
function report(model:MLModel, driftType:MLDriftReport["driftType"], magnitude:number, threshold:number, severity:MLDriftReport["severity"], now:Date):MLDriftReport { return {id:crypto.randomUUID(),modelId:model.id,modelType:model.modelType,modelVersion:model.version,driftType,magnitude,threshold,severity,detectedAt:now.toISOString()} }
export function createDriftMonitorPoller(options:{intervalMs?:number}={}){ let timer:ReturnType<typeof setInterval>|undefined; return {start(){ if(timer) return; timer=setInterval(()=>void runDriftMonitor(),options.intervalMs??86_400_000); void runDriftMonitor()}, stop(){ if(timer) clearInterval(timer); timer=undefined }} }
