// Package capacity is the L10 analytical capacity planner (CC-SPEC-001 §10.3, §10.8, §24).
//
// The platform must serve Tamil Nadu's full school system — ~1.27 crore students across ~69,000 schools —
// with peak surges (exam results, admission windows). "Scale-proven" begins with an analytical model that
// SIZES the topology for a target load and then VALIDATES a proposed topology against the requirement, before
// a single node is provisioned. The empirical 1-crore proof runs on the dedicated load rig (BLOCKERS B-032);
// this model is the design-time gate that the rig later confirms. Deterministic + stdlib-only.
package capacity

import (
	"errors"
	"math"
)

// TamilNaduStudents and TamilNaduSchools are the production target population (§ brochure scope).
const (
	TamilNaduStudents = 12_700_000 // ~1.27 crore
	TamilNaduSchools  = 69_000
)

// Load describes the demand to size for.
type Load struct {
	Students           int     // total registered students
	Schools            int     // total schools
	PeakConcurrencyPct float64 // fraction of students simultaneously active at peak (e.g. 0.25 = 25%)
	RPSPerActiveUser   float64 // requests/sec generated by one active user
	SurgeFactor        float64 // multiply peak by this for surge planning (e.g. 2.0 for the 2-crore surge)
}

// Topology is a proposed (or required) deployment shape.
type Topology struct {
	ShardCount       int // distributed-table shards (Citus)
	AppNodes         int // stateless app/serving nodes
	DBNodes          int // database worker nodes
	ShardRowCapacity int // rows one shard holds comfortably
	NodeRPSCapacity  float64
	ReplicationF     int // replication factor (DB)
}

// Plan is the computed requirement.
type Plan struct {
	PeakActiveUsers  int
	PeakRPS          float64
	SurgeRPS         float64
	RequiredShards   int
	RequiredAppNodes int
	RequiredDBNodes  int
	HeadroomPct      float64
}

// HeadroomPct: provision this much spare capacity above the surge requirement.
const HeadroomPct = 0.30

// Compute sizes the topology required to serve a load (with surge + headroom).
func Compute(l Load) (Plan, error) {
	if l.Students <= 0 || l.Schools <= 0 {
		return Plan{}, errors.New("capacity: students and schools must be positive")
	}
	if l.PeakConcurrencyPct <= 0 || l.PeakConcurrencyPct > 1 {
		return Plan{}, errors.New("capacity: peak concurrency must be in (0,1]")
	}
	if l.RPSPerActiveUser <= 0 {
		return Plan{}, errors.New("capacity: RPS per active user must be positive")
	}
	surge := l.SurgeFactor
	if surge < 1 {
		surge = 1
	}
	peakActive := int(math.Ceil(float64(l.Students) * l.PeakConcurrencyPct))
	peakRPS := float64(peakActive) * l.RPSPerActiveUser
	surgeRPS := peakRPS * surge
	return Plan{
		PeakActiveUsers:  peakActive,
		PeakRPS:          peakRPS,
		SurgeRPS:         surgeRPS,
		RequiredShards:   0, // filled by SizeFor against a topology's per-unit capacities
		RequiredAppNodes: 0,
		RequiredDBNodes:  0,
		HeadroomPct:      HeadroomPct,
	}, nil
}

// SizeFor computes the required node/shard counts for a load against a topology's per-unit capacities,
// including surge and headroom. The topology's count fields are ignored (they are the proposal to validate).
func SizeFor(l Load, t Topology) (Plan, error) {
	p, err := Compute(l)
	if err != nil {
		return Plan{}, err
	}
	if t.ShardRowCapacity <= 0 || t.NodeRPSCapacity <= 0 || t.ReplicationF <= 0 {
		return Plan{}, errors.New("capacity: topology per-unit capacities must be positive")
	}
	withHeadroom := func(x float64) float64 { return x * (1 + HeadroomPct) }

	// shards sized by data volume (rows ≈ students), with headroom
	p.RequiredShards = ceilDiv(int(withHeadroom(float64(l.Students))), t.ShardRowCapacity)
	// app nodes sized by surge RPS, with headroom
	p.RequiredAppNodes = int(math.Ceil(withHeadroom(p.SurgeRPS) / t.NodeRPSCapacity))
	// DB nodes: at least the shard count, times replication, headroomed
	dbBase := p.RequiredShards * t.ReplicationF
	p.RequiredDBNodes = int(math.Ceil(withHeadroom(float64(dbBase))))
	return p, nil
}

// ValidationResult reports whether a proposed topology meets the requirement.
type ValidationResult struct {
	OK       bool
	Required Plan
	Failures []string
}

// Validate checks a proposed topology against the requirement for a load.
func Validate(l Load, proposed Topology) (ValidationResult, error) {
	req, err := SizeFor(l, proposed)
	if err != nil {
		return ValidationResult{}, err
	}
	var fail []string
	if proposed.ShardCount < req.RequiredShards {
		fail = append(fail, "insufficient shards")
	}
	if proposed.AppNodes < req.RequiredAppNodes {
		fail = append(fail, "insufficient app nodes")
	}
	if proposed.DBNodes < req.RequiredDBNodes {
		fail = append(fail, "insufficient db nodes")
	}
	return ValidationResult{OK: len(fail) == 0, Required: req, Failures: fail}, nil
}

func ceilDiv(a, b int) int {
	if b == 0 {
		return 0
	}
	return (a + b - 1) / b
}

// TamilNaduLoad is the canonical TN peak load (25% peak concurrency, 0.5 rps/active, 2× surge headroom).
func TamilNaduLoad() Load {
	return Load{
		Students:           TamilNaduStudents,
		Schools:            TamilNaduSchools,
		PeakConcurrencyPct: 0.25,
		RPSPerActiveUser:   0.5,
		SurgeFactor:        2.0,
	}
}
